-- ============================================================
-- Web3 成长之旅 · Supabase 数据库初始化脚本 v2
-- ⚠️ 注意：此脚本会删除并重建以下表：
--   ores, cards, card_ores, badges, badge_cards
-- 如有旧数据请提前备份！
--
-- 使用方法：
--   Supabase 控制台 → SQL Editor → New query → 粘贴运行
-- ============================================================

-- ── 删除旧表（级联删除关联数据）──────────────────────────────
drop table if exists badge_cards  cascade;
drop table if exists card_ores    cascade;
drop table if exists badges       cascade;
drop table if exists cards        cascade;
drop table if exists ores         cascade;

-- ── 矿石表（灵光碎片）─────────────────────────────────────────
create table ores (
  id         bigint generated by default as identity primary key,
  title      text    not null,
  content    text    not null,
  type       text    not null default 'text',
  tags       text[]  not null default '{}',
  created_at timestamptz not null default now()
);

-- ── 卡片表（成长结晶）─────────────────────────────────────────
create table cards (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text not null default '',
  rarity      text not null default 'common',
  created_at  timestamptz not null default now()
);

-- ── 卡片-矿石关联表 ───────────────────────────────────────────
create table card_ores (
  id      bigint generated by default as identity primary key,
  card_id bigint not null references cards(id) on delete cascade,
  ore_id  bigint not null references ores(id)  on delete cascade
);

-- ── 勋章表（SBT）─────────────────────────────────────────────
create table badges (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text not null default '',
  token_id    text not null unique,
  created_at  timestamptz not null default now()
);

-- ── 勋章-卡片关联表 ───────────────────────────────────────────
create table badge_cards (
  id       bigint generated by default as identity primary key,
  badge_id bigint not null references badges(id) on delete cascade,
  card_id  bigint not null references cards(id)  on delete cascade
);

-- ── Row Level Security ────────────────────────────────────────
alter table ores        enable row level security;
alter table cards       enable row level security;
alter table card_ores   enable row level security;
alter table badges      enable row level security;
alter table badge_cards enable row level security;

-- service_role key 全权策略（后端使用）
create policy "service_role_ores"        on ores        for all using (true) with check (true);
create policy "service_role_cards"       on cards       for all using (true) with check (true);
create policy "service_role_card_ores"   on card_ores   for all using (true) with check (true);
create policy "service_role_badges"      on badges      for all using (true) with check (true);
create policy "service_role_badge_cards" on badge_cards for all using (true) with check (true);

-- ── 验证建表结果 ──────────────────────────────────────────────
select table_name, column_name, data_type
from information_schema.columns
where table_schema = 'public'
  and table_name in ('ores','cards','card_ores','badges','badge_cards')
order by table_name, ordinal_position;
